const HOST_MICROFRONT = process.env.HOST_MICROFRONT
const PORT = process.env.PORT
const URL_API_INTERACCIONES = process.env.URL_API_INTERACCIONES
const URL_API_CLIENTES = process.env.URL_API_CLIENTES
const URL_API_AUTH = process.env.URL_API_AUTH
const GRANT_TYPE= process.env.GRANT_TYPE
const SCOPE = process.env.SCOPE
const KEY= process.env.KEY
const SECRET= process.env.SECRET
export { HOST_MICROFRONT, PORT, URL_API_INTERACCIONES , URL_API_CLIENTES, URL_API_AUTH, GRANT_TYPE, SCOPE , KEY , SECRET }
