const API_PERMISSIONS = process.env.API_PERMISSIONS
const API_USERS = process.env.API_USERS
const PATH_PROFILES = process.env.PATH_PROFILES
const PATH_PROFILES_DETAIL_ID = process.env.PATH_PROFILES_DETAIL_ID
const PATH_PROFILES_UPDATE_ID = process.env.PATH_PROFILES_UPDATE_ID
const PATH_USERS = process.env.PATH_USERS
const PATH_USERS_DETAIL_ID = process.env.PATH_USERS_DETAIL_ID
const PATH_REPORTS = process.env.PATH_REPORTS

export {
	API_PERMISSIONS,
	API_USERS,
	PATH_PROFILES,
	PATH_PROFILES_DETAIL_ID,
	PATH_PROFILES_UPDATE_ID,
	PATH_USERS,
	PATH_USERS_DETAIL_ID,
	PATH_REPORTS,
}
